export const JET_TYPES = [
  'CRJ7',
  'CRJ9',
  'CRJX',
  'B737',
  'B738',
  'B739',
  'B38M',
  'A220',
  'A319',
  'A320',
  'A321',
  'A20N',
  'A21N',
  'E135',
  'E145',
  'E190',
];

export const TEC_TYPES = ['C208', 'BE58', 'B350', 'C414', 'P212', 'BN2P', 'C408', 'DHC6', 'TBM9'];

export const GA_TYPES = ['C152', 'C172', 'C182', 'P28A', 'BE36', 'BE58'];

export const AIRLINES: Record<string, string> = {
  '9 to': 'UAL',
  'united airlines': 'UAL',
  tonight: 'UAL',
  united: 'UAL',
  'southwest airline': 'SWA',
  'so 1st': 'SWA',
  southwest: 'SWA',
  "moxie's": 'MXY',
  democracy: 'MXY',
  moxie: 'MXY',
  maxi: 'MXY',
  amoxicillin: 'MXY',
  'mox c': 'MXY',
  microsoft: 'MXY',
  'tier flight': 'FFT',
  "what's your flight": 'FFT',
  'run to your flight': 'FFT',
  'fun to your flight': 'FFT',
  'frontier flight': 'FFT',
  'frontier airline': 'FFT',
  frontier: 'FFT',
  'D airline': 'DAL',
  'delta airline': 'DAL',
  'down to': 'DAL',
  data: 'DAL',
  delta: 'DAL',
  D: 'DAL',
  'american airline': 'AAL',
  'mark in': 'AAL',
  merika: 'AAL',
  marika: 'AAL',
  american: 'AAL',
  america: 'AAL',
  kara: 'KAP',
  kerr: 'KAP',
  kr: 'KAP',
  k: 'KAP',
  care: 'KAP',
  carrot: 'KAP',
  'cape air': 'KAP',
  cara: 'KAP',
  fedex: 'FDX',
  'wiggins airways': 'WIG',
  weekends: 'WIG',
  weekend: 'WIG',
  wagons: 'WIG',
  wiggins: 'WIG',
  wigan: 'WIG',
  wigging: 'WIG',
};

export const AIRLINE_CODES: Record<string, string> = {
  UAL: 'united',
  SWA: 'southwest',
  MXY: 'moxie',
  FFT: 'frontier flight',
  DAL: 'delta',
  AAL: 'american',
  KAP: 'care',
  FDX: 'fedex',
  WIG: 'wiggins airways',
};
