export const DEST_TO_DIRECTION_MAP: Record<
  string,
  'west' | 'east' | undefined
> = {
  //H
  KBWI: 'west',
  KCLE: 'west',
  KCLT: 'west',
  KCVG: 'west',
  KDCA: 'west',
  KDTW: 'west',
  KEWR: 'west',
  KHPN: 'west',
  KIAD: 'west',
  KJFK: 'west',
  KLGA: 'west',
  KMCO: 'west',
  KMIA: 'west',
  KMSP: 'west',
  KORD: 'west',
  KPBI: 'west',
  KPHL: 'west',
  KPIT: 'west',
  KRDU: 'west',
  KRSW: 'west',
  KSRQ: 'west',
  KTPA: 'west',
  //TEC
  KACK: 'west',
  KALB: 'west',
  KBDL: 'west',
  KBDR: 'west',
  KBED: 'west',
  KBOS: 'west',
  KDXR: 'west',
  KFRG: 'west',
  KGON: 'west',
  KHFD: 'west',
  KHVN: 'west',
  KHYA: 'west',
  KISP: 'west',
  KMVY: 'west',
  KORH: 'west',
  KOWD: 'west',
  KOXC: 'west',
  KPNE: 'west',
  KPVC: 'west',
  KPVD: 'west',
  KSWF: 'west',
};
